SELECT
    c.Name AS `Chore`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'DailyChore' AND pc.priority = 0 THEN p.Name END SEPARATOR ', ') AS `Daily (Low)`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'DailyChore' AND pc.priority = 1 THEN p.Name END SEPARATOR ', ') AS `Daily (Medium)`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'DailyChore' AND pc.priority = 2 THEN p.Name END SEPARATOR ', ') AS `Daily (High)`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'WeeklyChore' AND pc.DayOfWeek = 'Sunday'    THEN p.Name END SEPARATOR ', ') AS `Sunday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'WeeklyChore' AND pc.DayOfWeek = 'Monday'    THEN p.Name END SEPARATOR ', ') AS `Monday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'WeeklyChore' AND pc.DayOfWeek = 'Tuesday'   THEN p.Name END SEPARATOR ', ') AS `Tuesday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'WeeklyChore' AND pc.DayOfWeek = 'Wednesday' THEN p.Name END SEPARATOR ', ') AS `Wednesday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'WeeklyChore' AND pc.DayOfWeek = 'Thursday'  THEN p.Name END SEPARATOR ', ') AS `Thursday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'WeeklyChore' AND pc.DayOfWeek = 'Friday'    THEN p.Name END SEPARATOR ', ') AS `Friday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'WeeklyChore' AND pc.DayOfWeek = 'Saturday'  THEN p.Name END SEPARATOR ', ') AS `Saturday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 1  THEN p.Name END SEPARATOR ', ') AS `Month Day 1`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 2  THEN p.Name END SEPARATOR ', ') AS `Month Day 2`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 3  THEN p.Name END SEPARATOR ', ') AS `Month Day 3`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 4  THEN p.Name END SEPARATOR ', ') AS `Month Day 4`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 5  THEN p.Name END SEPARATOR ', ') AS `Month Day 5`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 6  THEN p.Name END SEPARATOR ', ') AS `Month Day 6`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 7  THEN p.Name END SEPARATOR ', ') AS `Month Day 7`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 8  THEN p.Name END SEPARATOR ', ') AS `Month Day 8`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 9  THEN p.Name END SEPARATOR ', ') AS `Month Day 9`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 10 THEN p.Name END SEPARATOR ', ') AS `Month Day 10`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 11 THEN p.Name END SEPARATOR ', ') AS `Month Day 11`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 12 THEN p.Name END SEPARATOR ', ') AS `Month Day 12`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 13 THEN p.Name END SEPARATOR ', ') AS `Month Day 13`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 14 THEN p.Name END SEPARATOR ', ') AS `Month Day 14`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 15 THEN p.Name END SEPARATOR ', ') AS `Month Day 15`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 16 THEN p.Name END SEPARATOR ', ') AS `Month Day 16`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 17 THEN p.Name END SEPARATOR ', ') AS `Month Day 17`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 18 THEN p.Name END SEPARATOR ', ') AS `Month Day 18`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 19 THEN p.Name END SEPARATOR ', ') AS `Month Day 19`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 20 THEN p.Name END SEPARATOR ', ') AS `Month Day 20`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 21 THEN p.Name END SEPARATOR ', ') AS `Month Day 21`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 22 THEN p.Name END SEPARATOR ', ') AS `Month Day 22`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 23 THEN p.Name END SEPARATOR ', ') AS `Month Day 23`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 24 THEN p.Name END SEPARATOR ', ') AS `Month Day 24`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 25 THEN p.Name END SEPARATOR ', ') AS `Month Day 25`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 26 THEN p.Name END SEPARATOR ', ') AS `Month Day 26`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 27 THEN p.Name END SEPARATOR ', ') AS `Month Day 27`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 28 THEN p.Name END SEPARATOR ', ') AS `Month Day 28`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 29 THEN p.Name END SEPARATOR ', ') AS `Month Day 29`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 30 THEN p.Name END SEPARATOR ', ') AS `Month Day 30`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.DayOfMonth = 31 THEN p.Name END SEPARATOR ', ') AS `Month Day 31`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 0 AND pc.Day = 0 THEN p.Name END SEPARATOR ', ') AS `First Sunday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 0 AND pc.Day = 1 THEN p.Name END SEPARATOR ', ') AS `First Monday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 0 AND pc.Day = 2 THEN p.Name END SEPARATOR ', ') AS `First Tuesday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 0 AND pc.Day = 3 THEN p.Name END SEPARATOR ', ') AS `First Wednesday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 0 AND pc.Day = 4 THEN p.Name END SEPARATOR ', ') AS `First Thursday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 0 AND pc.Day = 5 THEN p.Name END SEPARATOR ', ') AS `First Friday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 0 AND pc.Day = 6 THEN p.Name END SEPARATOR ', ') AS `First Saturday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 1 AND pc.Day = 0 THEN p.Name END SEPARATOR ', ') AS `Second Sunday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 1 AND pc.Day = 1 THEN p.Name END SEPARATOR ', ') AS `Second Monday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 1 AND pc.Day = 2 THEN p.Name END SEPARATOR ', ') AS `Second Tuesday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 1 AND pc.Day = 3 THEN p.Name END SEPARATOR ', ') AS `Second Wednesday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 1 AND pc.Day = 4 THEN p.Name END SEPARATOR ', ') AS `Second Thursday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 1 AND pc.Day = 5 THEN p.Name END SEPARATOR ', ') AS `Second Friday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 1 AND pc.Day = 6 THEN p.Name END SEPARATOR ', ') AS `Second Saturday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 2 AND pc.Day = 0 THEN p.Name END SEPARATOR ', ') AS `Third Sunday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 2 AND pc.Day = 1 THEN p.Name END SEPARATOR ', ') AS `Third Monday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 2 AND pc.Day = 2 THEN p.Name END SEPARATOR ', ') AS `Third Tuesday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 2 AND pc.Day = 3 THEN p.Name END SEPARATOR ', ') AS `Third Wednesday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 2 AND pc.Day = 4 THEN p.Name END SEPARATOR ', ') AS `Third Thursday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 2 AND pc.Day = 5 THEN p.Name END SEPARATOR ', ') AS `Third Friday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 2 AND pc.Day = 6 THEN p.Name END SEPARATOR ', ') AS `Third Saturday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 3 AND pc.Day = 0 THEN p.Name END SEPARATOR ', ') AS `Fourth Sunday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 3 AND pc.Day = 1 THEN p.Name END SEPARATOR ', ') AS `Fourth Monday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 3 AND pc.Day = 2 THEN p.Name END SEPARATOR ', ') AS `Fourth Tuesday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 3 AND pc.Day = 3 THEN p.Name END SEPARATOR ', ') AS `Fourth Wednesday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 3 AND pc.Day = 4 THEN p.Name END SEPARATOR ', ') AS `Fourth Thursday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 3 AND pc.Day = 5 THEN p.Name END SEPARATOR ', ') AS `Fourth Friday`,
    GROUP_CONCAT(DISTINCT CASE WHEN pc.Discriminator = 'MonthlyChore' AND pc.Week = 3 AND pc.Day = 6 THEN p.Name END SEPARATOR ', ') AS `Fourth Saturday`
FROM PersonChores pc
INNER JOIN Chore c  ON pc.ChoreId  = c.Id
INNER JOIN People p ON pc.PersonId = p.Id
WHERE pc.IsActive = 1
GROUP BY c.Id, c.Name
ORDER BY c.Name;
