using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace marvin2.Models
{
    /// <summary>
    /// Represents a generic chore/task with a name, description, and optional notes.
    /// This is the base model persisted in the database for chores.
    /// </summary>
    public class Chore
    {
        /// <summary>
        /// Primary key for the chore. Value is generated by the database.
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        
        /// <summary>
        /// Short display name for the chore.
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// Detailed description of what the chore entails.
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Optional free-form notes related to the chore (e.g., instructions or history).
        /// </summary>
        public string? Notes { get; set; }
    }
}