using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace marvin2.Models
{
    /// <summary>
    /// Represents a single subdirectory ("title") observed inside one of the monitored
    /// media folders (e.g. movies, music, shows). Persisting these rows lets
    /// <c>MediaFolderService</c> detect additions and removals across restarts by
    /// comparing the current directory listing against the last known state stored here.
    /// </summary>
    public class MediaFolderItem
    {
        /// <summary>
        /// Primary key for the media folder item. The value is generated by the database.
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Identifies which monitored folder this title belongs to (e.g. "Movies", "Music", "Shows").
        /// Matches the <c>Key</c> of the corresponding entry in the <c>MediaFolders</c> configuration section.
        /// </summary>
        public string FolderKey { get; set; }

        /// <summary>
        /// The subdirectory name, treated as the title of the media item.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// The date and time this title was first observed on disk.
        /// </summary>
        public DateTime FirstSeenAt { get; set; }
    }
}
