using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace marvin2.Models
{
    /// <summary>
    /// Represents a score record associated with a person.
    /// Tracks score changes over time with timestamps.
    /// </summary>
    public class PersonScore
    {
        /// <summary>
        /// Primary key for the person score record. The value is generated by the database.
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PersonScoreId { get; set; }

        /// <summary>
        /// Foreign key reference to the person this score belongs to.
        /// </summary>
        [ForeignKey("Person")]
        public int PersonId { get; set; }

        /// <summary>
        /// The score value. Defaults to 0.
        /// </summary>
        public int Score { get; set; } = 0;

        /// <summary>
        /// The date and time when this score record was created.
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// The date and time when this score record was last updated.
        /// </summary>
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Navigation property to the associated person.
        /// </summary>
        public Person Person { get; set; }
    }
}
