using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Tools;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace marvin2.Models
{
    /// <summary>
    /// Represents an individual who can be assigned chores.
    /// This model is persisted in the database and contains a primary key and a display name.
    /// </summary>
    public class Person
    {
        /// <summary>
        /// Primary key for the person. The value is generated by the database.
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Display name of the person. This is used when assigning and listing chores.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Constructs a new <see cref="Person"/> with the specified display name.
        /// </summary>
        /// <param name="name">The display name for the person.</param>
        public Person(string name)
        {
            Name = name;
        }
    }
}