// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using marvin2.Models;

#nullable disable

namespace data.Migrations
{
    [DbContext(typeof(ChoreContext))]
    [Migration("20251001030000_AddPersonScoreTable")]
    partial class AddPersonScoreTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("marvin2.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Chore");
                });

            modelBuilder.Entity("marvin2.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("marvin2.Models.PersonScore", b =>
                {
                    b.Property<int>("PersonScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PersonScoreId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PersonScoreId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonScores");
                });

            modelBuilder.Entity("marvin2.Models.PersonChore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChoreId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("longtext");

                    b.Property<int?>("Week")
                        .HasColumnType("int");

                    b.Property<int?>("priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonChores");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PersonChore");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("marvin2.Models.DailyChore", b =>
                {
                    b.HasBaseType("marvin2.Models.PersonChore");

                    b.Property<int>("priority")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DailyChore");
                });

            modelBuilder.Entity("marvin2.Models.MonthlyChore", b =>
                {
                    b.HasBaseType("marvin2.Models.PersonChore");

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<int?>("Week")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MonthlyChore");
                });

            modelBuilder.Entity("marvin2.Models.WeeklyChore", b =>
                {
                    b.HasBaseType("marvin2.Models.PersonChore");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("WeeklyChore");
                });

            modelBuilder.Entity("marvin2.Models.PersonChore", b =>
                {
                    b.HasOne("marvin2.Models.Chore", "Chore")
                        .WithMany()
                        .HasForeignKey("ChoreId");

                    b.HasOne("marvin2.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Chore");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("marvin2.Models.PersonScore", b =>
                {
                    b.HasOne("marvin2.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
